version: '3'

name: 'Filmovi recenzije'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/admin/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - ./backend:/app

    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:

