# Generated by Django 4.2.15 on 2024-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
