# Generated by Django 4.2.15 on 2024-08-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="app.genre"),
        ),
    ]
