# Generated by Django 4.2.15 on 2024-08-18 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_movie_actors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
    ]
