# Generated by Django 4.2.15 on 2024-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_genre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-time"]},
        ),
        migrations.AddField(
            model_name="review",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
