# Generated by Django 4.2.15 on 2024-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_movie_options_alter_review_options_review_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="name",
            new_name="title",
        ),
    ]
