# Generated by Django 4.2.15 on 2024-08-20 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_movie_options_rename_name_movie_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="review",
            name="username",
        ),
    ]
